plugins {
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.jetbrainsKotlinAndroid)
    alias(libs.plugins.hiltDagger)
    alias(libs.plugins.pluginSerialize)
    id 'kotlin-kapt'
    id 'kotlin-parcelize'
}

android {
    signingConfigs {
        release {
            storeFile file('../moviebeam_prod.jks')
            storePassword 'diipl@123'
            keyAlias 'key0'
            keyPassword 'diipl@123'
        }
    }

    lint {
        baseline = file("lint-baseline.xml")
    }

    namespace 'com.diipl.moviebeam'
    compileSdk 33

    defaultConfig {
        applicationId "com.diipl.moviebeam"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName chromeCastVersion

    }

    applicationVariants.configureEach { variant ->
        variant.outputs.each { output ->
            if (variant.buildType.name == "chromeCast") {
                output.outputFileName = "Moviebeam_Prod_CC_v${chromeCastVersion}.apk"
            }else if (variant.buildType.name == "stb") {
                output.outputFileName = "Moviebeam_Prod_STB_v${stbVersion}.apk"
                output.versionNameOverride = stbVersion
            }
        }
    }

    buildFeatures {
        buildConfig true
        viewBinding = true
        dataBinding = true
        aidl = true
    }

    buildTypes {
        chromeCast {
            debuggable true
            minifyEnabled true
            shrinkResources true
            buildConfigField("String", "BUILD_TYPE", "\"CHROMECAST\"")
            buildConfigField("int", "BUILD_TYPE_ID", "4")
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        stb {
            minifyEnabled true
            shrinkResources true
            buildConfigField("String", "BUILD_TYPE", "\"STB\"")
            buildConfigField("int", "BUILD_TYPE_ID", "5")
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        targetCompatibility JavaVersion.VERSION_1_8
        sourceCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8
    }

}

dependencies {

    implementation(libs.androidx.core.ktx)
    implementation libs.androidx.annotation
    implementation libs.androidx.leanback
    implementation libs.glide
    implementation libs.kotlin.stdlib.jdk8
    implementation libs.androidx.constraintlayout
    implementation libs.material
    implementation libs.androidx.activity

    //android support
    implementation libs.androidx.appcompat

    // ViewModel
    implementation(libs.androidx.lifecycle.viewmodel.ktx)
    implementation libs.androidx.lifecycle.extensions

    // LiveData
    implementation libs.androidx.lifecycle.runtime.ktx
    implementation(libs.androidx.lifecycle.livedata.ktx)

    // retrofit
    implementation(libs.retrofit)
    implementation(libs.converter.scalars)
    implementation(libs.retrofit.converter.gson)

    //okhttp
    implementation(libs.okhttp)
    implementation(libs.logging.interceptor)

    // hilt
    implementation(libs.hilt.android)
    kapt(libs.hilt.android.compiler)

    implementation libs.androidx.fragment.ktx

    // Coroutines
    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.kotlinx.coroutines.android)

    // WorkManager
    implementation libs.androidx.work.runtime.ktx
    implementation(libs.androidx.hilt.work)
    kapt(libs.androidx.hilt.compiler)

    kapt libs.databinding.compiler

    // DataStore
    implementation libs.androidx.datastore

    // Preferences DataStore
    implementation libs.androidx.datastore.preferences

    // kotlinx serialization
    implementation libs.kotlinx.serialization.json

    // ExoPlayer
    implementation libs.androidx.media3.exoplayer
    implementation libs.androidx.media3.exoplayer.dash
    implementation libs.androidx.media3.ui
    implementation libs.androidx.media3.exoplayer.hls

    implementation(libs.zxing.core)
    implementation libs.kotlin.reflect

    implementation libs.androidx.room.ktx
    kapt libs.androidx.room.compiler

    //carousel
    implementation libs.androidx.viewpager2

}

kapt {
    correctErrorTypes true
}