package com.diipl.moviebeam.dtv;

public class DvbConstant {
    public static final String ACTION_SEARCH_DVB_CHANNEL = "com.nes.intent.action.search.channel";
    public static final int ANTENNA_POWER_OFF = 0;
    public static final int ANTENNA_POWER_ON = 1;
    public static final String DVB_CONFIG_SERVICE = "org.dtvkit.inputsource.service.DvbScanConfigService";
    public static final String DVB_INPUT_SOURCE_PACKAGE = "org.dtvkit.inputsource";
    public static final String KEY_CHANNEL_FREQUENCY = "channelFrequency";
    public static final String KEY_CURRENT_LOCK_TIME = "current_lock_time";
    public static final String KEY_DISEQC1_2_DISH_LIMITS_STATUS = "key_dish_limit_status";
    public static final String KEY_DISEQC1_2_DISH_MOVE_DIRECTION = "key_dish_move_direction";
    public static final String KEY_DISEQC1_2_DISH_MOVE_STEP = "key_dish_move_step";
    public static final String KEY_DVBT_BANDWIDTH = "dvbt_band_width";
    public static final String KEY_DVB_MODE = "dvb_mode";
    public static final String KEY_DVB_NIT_STATUS = "dvb_nit_status";
    public static final String KEY_DVB_SCAN_TYPE = "dvb_scan_type";
    public static final String KEY_DVB_SEARCH_TYPE = "dvb_search_type";
    public static final String KEY_DVB_SERVICE_TYPE = "dvb_service_type";
    public static final String KEY_DVB_TUNER_TYPE = "dvb_tuner_type";
    public static final String KEY_EWBS_LOCATION = "ewbs_location";
    public static final String KEY_IS_CLEAR_DATA = "is_clear_data";
    public static final String KEY_IS_FAST_SCAN = "is_fast_scan";
    public static final String KEY_IS_IF_IF_MODE = "is_if_if_mode";
    public static final String KEY_JSON_PARAM = "json_param";
    public static final String KEY_PUBLIC_FIRST_INSTALL = "public_first_install_mode";
    public static final String KEY_PUBLIC_SEARCH_MODE = "public_search_mode";
    public static final String KEY_SEARCH_DVB_CHANNEL_NAME = "dvb_channel_name";
    public static final String KEY_SEARCH_TYPE = "dvbType";
    public static final String KEY_SYMBOL_RATE = "symbolRate";
    public static final int LNB_TYPE_LNB_TYPE_OCS = 4;
    public static final int LNB_TYPE_SINGLE = 0;
    public static final int LNB_TYPE_UNICABLE = 2;
    public static final int LNB_TYPE_UNIVERSAL = 1;
    public static final int LNB_TYPE_USER_DEFIINED = 3;
    public static final int PARAMETER_ACTIVITY_RESULT_CODE = 1002;
    public static final int SEARCH_RESULT_ACTIVITY_RESULT_CODE = 1000;
    public static final String TV_KEY_AUTO_SYMBOL_SWITCH = "auto_symbol_switch";
    public static final String TV_KEY_AUTO_SYMBOL_VALUE = "auto_symbol_value";
    public static final String TV_KEY_DVBC_ANNEX_MODE = "dvbc_annex_mode";
    public static final String TV_KEY_LCN_SWITCH = "lcn_switch";
    public static final String TV_KEY_POWER_SWITCH = "power_switch";
    public static final String TV_KEY_SUBTITLE_SWITCH = "subtitle_switch";
}
